import type { ChatMessage, Participant } from "./types";

export const REMOTE_PARTICIPANTS: Participant[] = [
  {
    id: "sarah",
    identity: "sarah",
    name: "Sarah Chen",
    isHost: false,
    isLocal: false,
    isMuted: false,
    isCameraOff: false,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-sky-500/25 via-sky-500/10 to-background",
    status: "Product review",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
  {
    id: "mike",
    identity: "mike",
    name: "Mike Johnson",
    isHost: false,
    isLocal: false,
    isMuted: true,
    isCameraOff: false,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-amber-500/25 via-orange-500/10 to-background",
    status: "Listening",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
  {
    id: "emily",
    identity: "emily",
    name: "Emily Davis",
    isHost: false,
    isLocal: false,
    isMuted: false,
    isCameraOff: true,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-emerald-500/25 via-emerald-500/10 to-background",
    status: "Taking notes",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
  {
    id: "alex",
    identity: "alex",
    name: "Alex Turner",
    isHost: false,
    isLocal: false,
    isMuted: false,
    isCameraOff: false,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-fuchsia-500/25 via-rose-500/10 to-background",
    status: "Ready",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
];

export const CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "1",
    name: "Sarah Chen",
    time: "9:45 AM",
    message: "Slides look great. We can move to the rollout plan after this section.",
  },
  {
    id: "2",
    name: "Mike Johnson",
    time: "9:46 AM",
    message: "Please drop the final deck in chat when you're done presenting.",
  },
];
