import type { Participant } from "./types";

export const REMOTE_PARTICIPANTS: Participant[] = [
  {
    id: "sarah",
    identity: "sarah",
    name: "Sarah Chen",
    avatarSource: "sarah.chen@example.com",
    isHost: false,
    isLocal: false,
    handRaised: false,
    handRaisedAt: null,
    isMuted: false,
    isCameraOff: false,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-sky-500/25 via-sky-500/10 to-background",
    status: "Product review",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
  {
    id: "mike",
    identity: "mike",
    name: "Mike Johnson",
    avatarSource: "mike.johnson@example.com",
    isHost: false,
    isLocal: false,
    handRaised: false,
    handRaisedAt: null,
    isMuted: true,
    isCameraOff: false,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-amber-500/25 via-orange-500/10 to-background",
    status: "Listening",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
  {
    id: "emily",
    identity: "emily",
    name: "Emily Davis",
    avatarSource: "emily.davis@example.com",
    isHost: false,
    isLocal: false,
    handRaised: false,
    handRaisedAt: null,
    isMuted: false,
    isCameraOff: true,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-emerald-500/25 via-emerald-500/10 to-background",
    status: "Taking notes",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
  {
    id: "alex",
    identity: "alex",
    name: "Alex Turner",
    avatarSource: "alex.turner@example.com",
    isHost: false,
    isLocal: false,
    handRaised: false,
    handRaisedAt: null,
    isMuted: false,
    isCameraOff: false,
    isSpeaking: false,
    isScreenSharing: false,
    accentClassName: "from-fuchsia-500/25 via-rose-500/10 to-background",
    status: "Ready",
    cameraTrack: null,
    audioTrack: null,
    screenShareTrack: null,
  },
];
